DROP TABLE IF EXISTS "EVENT_SPONSOR";
DROP TABLE IF EXISTS "EVENT";
DROP TABLE IF EXISTS "SPONSOR";

CREATE TABLE SPONSOR (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    "NAME" TEXT,
    INDUSTRY TEXT
);
CREATE TABLE EVENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    "NAME" TEXT,
    "DATE" TEXT
);
CREATE TABLE EVENT_SPONSOR (
    SPONSORID INT,
    EVENTID INT,
    PRIMARY KEY (SPONSORID, EVENTID),
    FOREIGN KEY (SPONSORID) REFERENCES SPONSOR(ID),
    FOREIGN KEY (EVENTID) REFERENCES "EVENT"(ID)
);